/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkspacesRouteImport } from './routes/app.workspaces'
import { Route as AppSalvosRouteImport } from './routes/app.salvos'
import { Route as AppResultadoRouteImport } from './routes/app.resultado'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppJogosRouteImport } from './routes/app.jogos'
import { Route as AppJogadoresRouteImport } from './routes/app.jogadores'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppExplorarRouteImport } from './routes/app.explorar'
import { Route as AppEquipesRouteImport } from './routes/app.equipes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppSalvosRoute = AppSalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => AppRoute,
} as any)
const AppResultadoRoute = AppResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppJogosRoute = AppJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AppRoute,
} as any)
const AppJogadoresRoute = AppJogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorarRoute = AppExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipesRoute = AppEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/equipes': typeof AppEquipesRoute
  '/app/explorar': typeof AppExplorarRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/jogadores': typeof AppJogadoresRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/resultado': typeof AppResultadoRoute
  '/app/salvos': typeof AppSalvosRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/equipes': typeof AppEquipesRoute
  '/app/explorar': typeof AppExplorarRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/jogadores': typeof AppJogadoresRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/resultado': typeof AppResultadoRoute
  '/app/salvos': typeof AppSalvosRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/equipes': typeof AppEquipesRoute
  '/app/explorar': typeof AppExplorarRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/jogadores': typeof AppJogadoresRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/resultado': typeof AppResultadoRoute
  '/app/salvos': typeof AppSalvosRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/equipes'
    | '/app/explorar'
    | '/app/historico'
    | '/app/jogadores'
    | '/app/jogos'
    | '/app/perfil'
    | '/app/resultado'
    | '/app/salvos'
    | '/app/workspaces'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/equipes'
    | '/app/explorar'
    | '/app/historico'
    | '/app/jogadores'
    | '/app/jogos'
    | '/app/perfil'
    | '/app/resultado'
    | '/app/salvos'
    | '/app/workspaces'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/equipes'
    | '/app/explorar'
    | '/app/historico'
    | '/app/jogadores'
    | '/app/jogos'
    | '/app/perfil'
    | '/app/resultado'
    | '/app/salvos'
    | '/app/workspaces'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspaces': {
      id: '/app/workspaces'
      path: '/workspaces'
      fullPath: '/app/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salvos': {
      id: '/app/salvos'
      path: '/salvos'
      fullPath: '/app/salvos'
      preLoaderRoute: typeof AppSalvosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resultado': {
      id: '/app/resultado'
      path: '/resultado'
      fullPath: '/app/resultado'
      preLoaderRoute: typeof AppResultadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogos': {
      id: '/app/jogos'
      path: '/jogos'
      fullPath: '/app/jogos'
      preLoaderRoute: typeof AppJogosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogadores': {
      id: '/app/jogadores'
      path: '/jogadores'
      fullPath: '/app/jogadores'
      preLoaderRoute: typeof AppJogadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explorar': {
      id: '/app/explorar'
      path: '/explorar'
      fullPath: '/app/explorar'
      preLoaderRoute: typeof AppExplorarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipes': {
      id: '/app/equipes'
      path: '/equipes'
      fullPath: '/app/equipes'
      preLoaderRoute: typeof AppEquipesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEquipesRoute: typeof AppEquipesRoute
  AppExplorarRoute: typeof AppExplorarRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppJogadoresRoute: typeof AppJogadoresRoute
  AppJogosRoute: typeof AppJogosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppResultadoRoute: typeof AppResultadoRoute
  AppSalvosRoute: typeof AppSalvosRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEquipesRoute: AppEquipesRoute,
  AppExplorarRoute: AppExplorarRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppJogadoresRoute: AppJogadoresRoute,
  AppJogosRoute: AppJogosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppResultadoRoute: AppResultadoRoute,
  AppSalvosRoute: AppSalvosRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
